### ISSUE TITLE
Testing connection / How to query LDAP

### ISSUE THREAD

**Issue by martinklepsch** [activeldap/activeldap#10]
Hey,

I am currently trying to write a Rails app to manage all our users which are saved in LDAP.

```
development:                                                                    
    host: some.domain.com                                                       
    port: 4444                                                                    
    base: removed                                                                
    bind_dn: removed                                            
    password: removed
```

Problem is that I have no idea how I could test if this connection is set up properly.
I created some modules with the rails generate scripts that contain an ldap mapping

```
class Account < ActiveLdap::Base
 ldap_mapping :dn_attribute => "uid",
              :prefix => "ou=Accounts",
              :classes => ["top",
                        "shadowAccount",
                        "sambaSamAccount",
                        "posixAccount",
                        "person",
                        "organizationalPerson",
                        "mozillaAbPersonAlpha",
                        "inetOrgPerson",
                        "evolutionPerson",
                        "personalvw"
                        ]
end
```

Launching "rails c" then and typing "Account.exists?("existing_uid") never returns...

Are there any good ways to test the connection settings and retrieve some LDAP entries (just for testing purposes)?

Cheers & Thanks
