### ISSUE TITLE
Connect to multiple servers simultaneously

### ISSUE THREAD

**Issue by J-Verz** [activeldap/activeldap#204]
Hi,

Is there a way to connect to multiple servers like ActiveRecord? We have our own LDAP server and an external service we want to read data from and I couldn't figure out how to configure which model belongs to which server. A configuration file like this also throws the error `Unknown key: :server1.`:
```yaml
development:
  server1:
    host: ldap.example.com
    base: dc=example,dc=com
    bind_dn: cn=admin,dc=example,dc=com
    password: justanexample
  server2:
    host: ldap.nonexistent.com
    base: dc=nonexistent,dc=com
    bind_dn: cn=noboby,dc=nonexistent,dc=com
    password: thisisanexample
```
